### ISSUE TITLE
refactor get_topic_names_and_types

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rmw#105]
Given that namespaces are supported by now, we should refactor the rmw interface to not only give one accumulated list of all topics, but rather distinguish them between publishers, subscribers, services and clients.

**Comment by mikaelarguedas** [comment]
@Karsten1987 do you plan to work on this in the near future or do you prefer to unassign this ticket ?

**Comment by Karsten1987** [comment]
i keep the ticket opened, however not working on it in the near future.

**Comment by wjwwood** [comment]
Closed by https://github.com/ros2/rmw/pull/110
