### ISSUE TITLE
Plumb PERSISTENT durability into RMW

### ISSUE THREAD

**Issue by clalancette** [ros2/rmw#113]
I don't know the full scope of doing this, but I know for sure that in order to get persistent durability, we'll need to add a new member to the durability_policy_t here: https://github.com/ros2/rmw/blob/master/rmw/include/rmw/types.h#L191 .  I'm sure there is other work to get it down to the RMW implementation properly.

**Comment by dirk-thomas** [comment]
We don't need `persistent` in order to mimic latching support. Actually we decided not to use the `persistent` durability since it extends the data lifetime beyond the lifetime of the entity which published it.

**Comment by mikaelarguedas** [comment]
Based on feedback and given that https://github.com/eProsima/Fast-RTPS/issues/120 has been closed I/m going to close this
