### ISSUE TITLE
Expose QOS settings for a topic

### ISSUE THREAD

**Issue by Myzhar** [ros2/rmw#151]
#### Feature description
Since a subscriber can receive a topic message only if its QOS profile is compatible with the QOS profile of the publisher a method to retrieve this information from the available topics should be very useful.

#### Implementation considerations
I think that the command
`$ ros2 topic info /topic`
can be a good place to introduce this important feature.

Ref: https://answers.ros.org/question/304946/ros2-retrieving-qos-settings-for-a-topic/

**Comment by emersonknapp** [comment]
This feature now exists! @mjcarroll can you close it? I don't have the access to do so.
