### ISSUE TITLE
Expose DDS Security Logging to topic or file

### ISSUE THREAD

**Issue by acrowell-soartech** [ros2/rmw#174]
#### Feature description

The DDS Security standard includes a Logging plugin that handles logging of security events to a special topic.  This is implemented and available in RTI Connext, but currently must be enabled via source code, and the corresponding configuration is not exposed in any way by RMW.  This should be changed to allow users to enable either DDS Security logging to the topic or a specified file through startup configuration.

#### Implementation considerations

One reasonable way to present this to the user would be to make this configurable via environment variables which, if set, can configure whether logging to the secure topic, to a file, or both are to be enabled.  For example, we could have:

```
RMW_SECURITY_LOG_TO_TOPIC=true/false
RMW_SECURITY_LOG_TO_FILE= <path to file>
```

The default setting in the absence of an override should be to log to the topic, but not to a file.

**Comment by mjcarroll** [comment]
There is additionally an issue tracking this in SROS2: https://github.com/ros2/sros2/issues/110, would it make more sense to live over there?

**Comment by acrowell-soartech** [comment]
Thanks for your quick response.  It very well might.  The main reason I chose to post it here is because once other implementations begin support the Logging plugin for DDS Security, it will eventually be configured through different mechanisms for each implementation, which seems like it would require some level of support in RMW.
I am somewhat new to this developer community, so I'm not entirely sure what makes the most sense.  I'll try and post this in the issue you linked to and see what they think.

Thanks!

**Comment by mjcarroll** [comment]
Yes, I think that the `sros2` issue will probably get the most relevant eyeballs, if there are things that needed to be added in `rmw`, we can address those via pull requests.

Thanks!
